### ISSUE TITLE
failed to start session 

### ISSUE THREAD

**Issue by sudo-ghost** [off-world/lightdm-tiny-greeter#2]
when i go to login it says failed to start session and im unsure of how to fix it

**Comment by manfromth3m0oN** [comment]
Ive seen a fix for this for bspwm, in that changing the `session` variable in `config.h` will change the lightdm session. I'm having the same error on i3 and am unsure of how to fix it because changing session in all relevant places still leads to this error

**Comment by sudo-ghost** [comment]
I’m guessing the fix would be to boot into a recovery mode and edit the config through a root shell

**Comment by manfromth3m0oN** [comment]
this sounds like a sensible solution, what window manager do you use?

**Comment by sudo-ghost** [comment]
i3. I fixed it by going into tty mode and just changing the config

**Comment by manfromth3m0oN** [comment]
Great, you can close the issue now

**Comment by tobiohlala** [comment]
please make sure a valid desktop-entry for the session to start exists in `/usr/share/xsessions` and set the `session` variable in `config.h` to contain its file name before compilation. As already stated if you missed this and can’t login because of that switch to another tty - edit `config.h` - `make` - `make install` - reboot to fix the issue.
